language: generic 

# docker needs super-user to run
sudo: required 

# download/install docker 
services: 
    - docker

before_install: 
    - docker build braintelligencePL/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true braintelligencePL/docker-react npm run test

