# This file is similar to this commands: 
# docker build -f Dockerfile.dev .
# docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/app IMAGE_ID

version: '3'

services:
    web: 
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - 3000:3000
        volumes: 
            - app/node_modules # exclude node_modules
            - .:/app           # create reference local <-> docker of all files

    tests: 
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - app/node_modules
            - .:/app
        command: ["npm", "run", "test"]