# Build: 
# docker build -f Dockerfile.dev .

# Run: 
# docker run -it -p 3000:3000 IMAGE_ID

# How to propagade changes to container? 
# docker run -p 3000:3000 -v $(pwd):/app IMAGE_ID 

# Map everything but node_modules
# docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/app IMAGE_ID

FROM node:alpine

WORKDIR /app

COPY package.json .
RUN npm install 

COPY . . 

CMD ["npm", "run", "start"]

